dsn: user:pass@tcp(127.0.0.1:4711)/enwiki_p
configtemplate: User:Yapperbot/Pruner/use
formatsjsonpageid: 64338959
defaultexpiredmsgtemplate: User:Yapperbot/Pruner/expired
defaulttalkmsgheader: You have been pruned from a list